jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: Build documentation
        run: yarn build
        working-directory: ./projects/documentation
  build-pool-time-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: Build pool-time-core
        run: yarn build
        working-directory: ./projects/pool-time-core
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: pool-time-core-dist
          path: projects/pool-time-core/dist
  build-react-pool-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: Build react-pool-time
        run: yarn build
        working-directory: ./projects/react-pool-time
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: react-pool-time-dist
          path: projects/react-pool-time/dist
  commitlint:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
  format:
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: ESLint
        run: yarn eslint:check
      - name: Prettier
        run: yarn prettier:check
    runs-on: ubuntu-latest
  release:
    if: github.ref == 'refs/heads/master'
    needs: ['build-documentation', 'build-react-pool-time', 'commitlint', 'format', 'test-react-pool-time']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Download @react-pool-time dist
        uses: actions/download-artifact@v1
        with:
          name: react-pool-time-dist
      - name: Move @react-pool-time dist
        shell: bash
        run: |
          mv react-pool-time-dist projects/react-pool-time/dist
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Release
        run: yarn semantic-release
        working-directory: ./projects/react-pool-time
  test-pool-time-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: Test react-pool-time
        run: yarn test:ci
        working-directory: ./projects/pool-time-core
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  test-react-pool-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: nvm
        name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        run: yarn --offline --frozen-lockfile
      - name: Test react-pool-time
        run: yarn test:ci
        working-directory: ./projects/react-pool-time
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
name: Continuous Integration
on: [push]
